layout_spectrum: 0.6817951
typography_spectrum: 0.9266686
color:
  saturation: 0.8005572
  lightness: 0.7109662
  brandStrength: 0.9769334
  rhythmicContrast: 0.03778702
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: MC Design Group
