name: DesignbyMC
favicon: null
layout_spectrum: 0.56996
typography_spectrum: 0.44123
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e7b9a2'
    - '#32332d'
    - '#d09063'
    - '#904c10'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
