name: MC Design Group
favicon: null
layout_spectrum: 0.6817951
typography_spectrum: 0.9266686
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5625
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
