name: DesignbyMC
favicon: null
layout_spectrum: 0
typography_spectrum: 0.45056
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dfd2cb'
    - '#494247'
    - '#818285'
    - '#282222'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
